### ISSUE TITLE
Formatting Mangled on Sony SGP511 Android 6.0.1, API 23

### ISSUE THREAD

**Issue by crookedneighbor** [braintree/restricted-input#27]
Got a report that characters could not be typed after a perma-character with `Sony SGP511 Android 6.0.1, API 23` device. 

Looks similar, but not quite the same as https://github.com/braintree/restricted-input/pull/25

**Comment by intelliot** [comment]
Followed up with the reporter and found that:
1. They resolved the issue by disabling formatting and closed the ticket.
2. It was likely on the Samsung Browser, which will be addressed by https://github.com/braintree/restricted-input/pull/31
