### ISSUE TITLE
Published artefact includes erroneous code.

### ISSUE THREAD

**Issue by koddsson** [braintree/restricted-input#43]
### General information

* Library version: 1.2.5
* Browser and OS: Chrome, OSX

### Issue description

The built artifact in the npm registry contains this piece of code:

```js
new RestrictedInput({
  element: document.querySelector('#credit-card'),
  pattern: '{{9999}} {{9999}} {{9999}} {{9999}}'
});

module.exports = RestrictedInput;
```

This ends up raising a run time exception when the library is imported and the page doesn't include a element with the id `credit-card`.

Interestingly this piece of code doesn't exist in the actual codebase but rather just the built artefact leading me to believe that it's some sort of publishing slip-up where the latest version wasn't built correctly before being pushed to `npm`.

If someone could republish with the correctly built artefact that would be 💯.

**Comment by crookedneighbor** [comment]
I don't think we were intending to send the dist folder to npm, but since we're doing it anyway, we can ensure that the file is built before we do it. 1.2.6 now includes the latest built file.

https://github.com/braintree/restricted-input/commit/0dfdc1c2af2d1683e8e8332972473319a9f706a7

**Comment by koddsson** [comment]
Thanks!
