### ISSUE TITLE
Format at initialization?

### ISSUE THREAD

**Issue by Scrum** [braintree/restricted-input#51]
What is the sacred meaning not to format at initialization?

**Comment by crookedneighbor** [comment]
Can you explain a little more about what you are asking?

**Comment by Scrum** [comment]
Yep :)

If i have input element with value 
```html
<input value="41111111">
```

and initialize `restricted-input`
```js
const formattedCreditCardInput = new RestrictedInput({
      element,
      pattern: '{{9999}} {{9999}}'
    });
```

The value in the input is not formatted. A basic strategy was chosen in which the 
```js
function BaseStrategy(options) {
  this.isFormatted = false;
  ...
}
```

and there is no explicit trigger for the value to be formatted

**Comment by Scrum** [comment]
I created a [demo](https://scrum.github.io/credit-card-gaps-pattern/) for a [credit-card-gaps-pattern](https://github.com/Scrum/credit-card-gaps-pattern) that creates a pattern for `restricted-input` in which you can watch as I clearly tryger call `setPattern` to initialize formatting

**Comment by crookedneighbor** [comment]
Having it set the pattern on initialization seems reasonable. Would you like to open a PR?

**Comment by Scrum** [comment]
@crookedneighbor Would you like to open a PR? Yep, in progress.

Would you be interested if I transferred to your org [credit-card-gaps-pattern](https://github.com/Scrum/credit-card-gaps-pattern) ?

**Comment by Scrum** [comment]
@crookedneighbor 
> Would you like to open a PR?

success #52

**Comment by crookedneighbor** [comment]
No, we do not wish to maintain credit-card-gaps-pattern at this time.

**Comment by Scrum** [comment]
no problem :)

**Comment by crookedneighbor** [comment]
This is out with v2.0.0
