### ISSUE TITLE
bug: input errors in Android Chrome

### ISSUE THREAD

**Issue by brandon-garcia** [braintree/restricted-input#95]
### General information

- Library version: 3.0.5
- Browser and OS: Chrome 101.0.4951.61 on Android 10; SM-G960U Build/QP1A.190711.020

### Issue description

https://codepen.io/brandon-garcia/pen/poaWzvg

If you load up the above codepen link on android chrome, tested myself with a samsung device, and type "123456"
You will sometimes see "1234 556" where the "5" keypress registered twice. This doesn't always happen but happens often enough that in 1 or 2 refreshes you should be able to get this behavior.

Other issues occasionally observed but not yet replicated via codepen:
- the "5" keypress doesn't register in the input
- the "6" keypress doesn't register in the input

**Comment by hollabaq86** [comment]
👋 @brandon-garcia thanks for the issue, we'll have someone take a look and follow up with feedback.

If you are able to reliably replicate certain numbers not being registered, please feel free to make a new issue with those steps so we can track these separately.

Thanks!

**Comment by hollabaq86** [comment]
Closing as we weren't able to replicate
